import "./globals.css";
import "../public/assets/font-awesome/css/font-awesome.min.css";

export const metadata = {
  title: "Learn NEXT.JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        {children}
      </body>
    </html>
  );
}
